---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/5 14:56
---
--批量注释 选中需要注释的内容，Ctrl + /
--批量块注释，选中需要注释的内容，Ctrl + Shift + /
--- 三条也是注释
--- 类似 Vs 的 /**/
print("Hello IDEA")
